export const SET_STUDENT = "SET_STUDENT";
export const SET_TEACHER = "SET_TEACHER";
export const SET_AUTOCOMPLETE_USERS = "SET_AUTOCOMPLETE_USERS";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_LOADED_USER_DATA = "SET_LOADED_USER_DATA";
export const SET_LOADED_STUDENT_DATA = "SET_LOADED_STUDENT_DATA";
export const SET_LOADED_TEACHER_DATA = "SET_LOADED_TEACHER_DATA";
export const SET_TYPE = "SET_TYPE";
export const SET_TOKEN = "SET_TOKEN";
export const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN";

export const SET_SCHOOL_DATA = "SET_SCHOOL_DATA";
export const SET_SCHOOL_INFO = "SET_SCHOOL_INFO";
export const PUSH_TO_SCHOOL_COURSES = "PUSH_TO_SCHOOL_COURSES";
export const PUSH_TO_SCHOOL_STUDENTS = "PUSH_TO_SCHOOL_STUDENTS";
export const PUSH_TO_SCHOOL_TEACHERS = "PUSH_TO_SCHOOL_TEACHERS";
export const REMOVE_FROM_SCHOOL_COURSES = "REMOVE_FROM_SCHOOL_COURSES";
export const REMOVE_FROM_SCHOOL_STUDENTS = "REMOVE_FROM_SCHOOL_STUDENTS";
export const REMOVE_FROM_SCHOOL_TEACHERS = "REMOVE_FROM_SCHOOL_TEACHERS";
export const SET_AUTOCOMPLETE_SCHOOLS = "SET_AUTOCOMPLETE_SCHOOLS";
export const SET_SCHOOL_TOKEN = "SET_SCHOOL_TOKEN";
export const SET_SCHOOL_LOGGED_IN = "SET_SCHOOL_LOGGED_IN";

export const SET_TEACHER_INFO = "SET_TEACHER_INFO";
export const SET_TEACHER_DATA = "SET_TEACHER_DATA";

export const SET_STUDENT_INFO = "SET_STUDENT_INFO";
export const SET_STUDENT_DATA = "SET_STUDENT_DATA";

export const SET_COURSE_INFO = "SET_COURSE_INFO";
export const SET_COURSE_DATA = "SET_COURSE_DATA";
export const PUSH_COURSE_CLASSES = "PUSH_COURSE_CLASSES";
export const EDIT_COURSE_CLASSES = "EDIT_COURSE_CLASSES";
export const REMOVE_FROM_COURSE_CLASSES = "REMOVE_FROM_COURSE_CLASSES";
